MvcBlog/Models/Blog.cs
using System.ComponentModel.DataAnnotations;

namespace MvcBlog.Models
{
    public class Blog
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Des { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Detail { get; set; }

        [Required]
        [Range(1, 10)]
        public int Category { get; set; }

        public string Public { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Data_pubblic { get; set; }

        [Required]
        public int Position { get; set; }

        public string Thumbs { get; set; }
    }
}

MvcBlog/Models/ErrorViewModel.cs
namespace MvcBlog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcBlog/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using MvcBlog.Data;

namespace MvcBlog.Models
{
    public class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MvcBlogContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<MvcBlogContext>>()))
            {
                // Look for any movies.
                if (context.Blog.Any())
                {
                    return;   // DB has been seeded
                }

                context.Blog.AddRange(
                    new Blog
                    {
                        Title = "When Harry Met Sally",
                        Des = "dawdawdaw",
                        Detail = "dawdawdawd",
                        Category = 1,
                        Public = "adw",
                        Data_pubblic = DateTime.Now,
                        Thumbs = "dawdawd"
                    }

                );
                context.SaveChanges();
            }
        }
    }
}

MvcBlog/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcBlog.Data;
using MvcBlog.Models;

namespace MvcBlog.Controllers
{
    public class BlogsController : Controller
    {
        private readonly MvcBlogContext _context;

        public BlogsController(MvcBlogContext context)
        {
            _context = context;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {

            return _context.Blog != null ?
                        View(await _context.Blog.ToListAsync()) :
                        Problem("Entity set 'MvcBlogContext.Blog'  is null.");
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Blog == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Des,Detail,Category,Public,Data_pubblic,Position,Thumbs")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Blog == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Des,Detail,Category,Public,Data_pubblic,Position,Thumbs")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Blog == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Blog == null)
            {
                return Problem("Entity set 'MvcBlogContext.Blog'  is null.");
            }
            var blog = await _context.Blog.FindAsync(id);
            if (blog != null)
            {
                _context.Blog.Remove(blog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return (_context.Blog?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        //public async Task<IActionResult> ConvertPosition(Blog blog)
        //{

        //}

        public async Task<IActionResult> Search(string searchString)
        {
            var blogs = from m in _context.Blog
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                blogs = blogs.Where(s => s.Title.Contains(searchString));
            }

            return View(await blogs.ToListAsync());
        }
    }
}

MvcBlog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcBlog.Models;
using System.Diagnostics;

namespace MvcBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Test()
        {
            return View();
        }
    }
}

MvcBlog/Views/Blogs/Create.cshtml
@model MvcBlog.Models.Blog

@{
    ViewData["Title"] = "Create";
}
<style>
    .card-title {
        padding: 10px;
        background-color: #f0f3f5;
    }
</style>
<div class="card">
    <h4 class="card-title">New Blogs</h4>
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-12">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Tiêu đề:</label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Mô tả ngắn:</label>
                            <textarea rows="4" asp-for="Des" class="form-control"></textarea>
                            <span asp-validation-for="Des" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Chi tiết:</label>
                            <textarea rows="4" asp-for="Detail" class="form-control"></textarea>
                            <span asp-validation-for="Detail" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-4 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Hình ảnh:</label>
                            <input asp-for="Thumbs" class="form-control" type="file" />
                            <span asp-validation-for="Thumbs" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <div class=" mb-1">Vị trí:</div>
                            <div class="d-flex align-content-center">
                                <div class="pe-3">
                                    <input id="1" name="Position" type="checkbox" value="1" />
                                    <label for="1" class="control-label">Việt Nam</label>
                                </div>
                                <div class="pe-3">
                                    <input id="2" name="Position" type="checkbox" value="2" />
                                    <label for="2" class="control-label">Châu Á</label>
                                </div>
                                <div class="pe-3">
                                    <input id="3" name="Position" type="checkbox" value="3" />
                                    <label for="3" class="control-label">Châu Âu</label>
                                </div>
                                <div class="pe-3">
                                    <input id="4" name="Position" type="checkbox" value="4" />
                                    <label for="4" class="control-label">Châu Mỹ</label>
                                </div>
                            </div>

                            <span asp-validation-for="Position" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <div class=" mb-1">Public:</div>
                            <div>
                                <input class="form-check-input" type="radio" value="true" name="Public" /> <label
                                    class="control-label">Yes</label>
                            </div>
                            <div>
                                <input class="form-check-input" type="radio" value="false" name="Public" /> <label
                                    class="control-label">No</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 row mb-2">
                        <div class="col-6">
                            <div class="form-group">
                                <label class="control-label mb-1">Loại:</label>
                                <input asp-for="Category" class="form-control" />
                                <span asp-validation-for="Category" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label class="control-label mb-1">Date pubblic:</label>
                                <input asp-for="Data_pubblic" class="form-control" />
                                <span asp-validation-for="Data_pubblic" class="text-danger"></span>
                            </div>
                        </div>


                    </div>

                    <div clasclass="form-group">
                        <button type="submit" value="Create" class="btn btn-success">Submit</button>
                        <button class="btn btn-primary" type="reset">Clear</button>
                    </div>

                </form>
            </div>
        </div>

        <div>


        </div>
    </div>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcBlog/Views/Blogs/Delete.cshtml
@model MvcBlog.Models.Blog

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete blog</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Public)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Public)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_pubblic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_pubblic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumbs)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" />
        <a class="btn btn-outline-secondary" asp-action="Index">Back to List</a>
    </form>
</div>

MvcBlog/Views/Blogs/Details.cshtml
@model MvcBlog.Models.Blog

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Blog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Detail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Detail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Public)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Public)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_pubblic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_pubblic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumbs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumbs)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcBlog/Views/Blogs/Edit.cshtml
@model MvcBlog.Models.Blog

@{
    ViewData["Title"] = "Edit";
}
<style>
    .card-title {
        padding: 10px;
        background-color: #f0f3f5;
    }
</style>
<div class="card">
    <h4 class="card-title">Edit Blogs</h4>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Tiêu đề:</label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Mô tả ngắn:</label>
                            <textarea rows="4" asp-for="Des" class="form-control"></textarea>
                            <span asp-validation-for="Des" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Chi tiết:</label>
                            <textarea rows="4" asp-for="Detail" class="form-control"></textarea>
                            <span asp-validation-for="Detail" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-4 mb-2">
                        <div class="form-group">
                            <label class="control-label mb-1">Hình ảnh:</label>
                            <input asp-for="Thumbs" class="form-control" type="file" />
                            <span asp-validation-for="Thumbs" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <div class=" mb-1">Vị trí:</div>
                            <div class="d-flex align-content-center">
                                <div class="pe-3">
                                    <input id="1" name="Position" type="checkbox" value="1" />
                                    <label for="1" class="control-label">Việt Nam</label>
                                </div>
                                <div class="pe-3">
                                    <input id="2" name="Position" type="checkbox" value="2" />
                                    <label for="2" class="control-label">Châu Á</label>
                                </div>
                                <div class="pe-3">
                                    <input id="3" name="Position" type="checkbox" value="3" />
                                    <label for="3" class="control-label">Châu Âu</label>
                                </div>
                                <div class="pe-3">
                                    <input id="4" name="Position" type="checkbox" value="4" />
                                    <label for="4" class="control-label">Châu Mỹ</label>
                                </div>
                            </div>

                            <span asp-validation-for="Position" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12 mb-2">
                        <div class="form-group">
                            <div class=" mb-1">Public:</div>
                            <div>
                                <input class="form-check-input" type="radio" value="true" name="Public" /> <label
                                    class="control-label">Yes</label>
                            </div>
                            <div>
                                <input class="form-check-input" type="radio" value="false" name="Public" /> <label
                                    class="control-label">No</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 row mb-2">
                        <div class="col-6">
                            <div class="form-group">
                                <label class="control-label mb-1">Loại:</label>
                                <input asp-for="Category" class="form-control" />
                                <span asp-validation-for="Category" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label class="control-label mb-1">Date pubblic:</label>
                                <input asp-for="Data_pubblic" class="form-control" />
                                <span asp-validation-for="Data_pubblic" class="text-danger"></span>
                            </div>
                        </div>


                    </div>
                    <div class="form-group">
                        <button type="submit" value="Save" class="btn btn-success">Submit</button>
                        <button class="btn btn-primary" asp-action="Index">Clear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcBlog/Views/Blogs/Index.cshtml
@model IEnumerable<MvcBlog.Models.Blog>

@{
    ViewData["Title"] = "Index";
}

@* <p>
    <a asp-action="Create">Create New</a>
    </p> *@
    <style>

    .card-title {
        padding: 10px;
        background-color: #f0f3f5;
    }
    </style>
<div class="card">
    <h4 class="card-title">List Blog</h4>
    <div class="card-body">
        <table class="table table-bordered align-middle text-center table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                       Tin
                    </th>
               @*     <th>
                        @Html.DisplayNameFor(model => model.Des)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Detail)
                    </th>*@
                    <th>
                        Loại
                    </th>
                    <th>
                        Trạng Thái
                    </th>
                    <th>
                        Vị trí
                    </th>
                    <th>
                       Ngày Public
                    </th>
                @* <th>
                        @Html.DisplayNameFor(model => model.Thumbs)
                    </th>*@
                
                    <th>
                        Edit
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td> <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                     @*   <td>
                            @Html.DisplayFor(modelItem => item.Des)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Detail)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Public)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Position)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Data_pubblic)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Thumbs)
                        </td>*@
                        <td>
                            <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a>

                        </td>
                        <td>
                            @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                            <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MvcBlog/Views/Blogs/Search.cshtml
@model IEnumerable<MvcBlog.Models.Blog>

@{
    ViewData["Title"] = "Search";
}
<style>

    .card-title {
        padding: 10px;
        background-color: #f0f3f5;
    }
</style>
<div class="body-page">
    <div class="card">
        <h4 class="card-title">Search Blog</h4>
        <div class="card-body">
            <form class="form-group row" asp-controller="Blogs" asp-action="Search">

                <div class=" row my-1 w-100">
                    <div class="col-sm-2 d-flex justify-content-center align-items-center">
                        <label for="inputSearch">Title:</label>
                    </div>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="SearchString" id="inputSearch" placeholder="Enter your title" />
                    </div>
                </div>
                <div class="d-flex mt-5 justify-content-center" style="flex: 1">
                    <button type="submit" class="btn btn-outline-success" value="Filter">
                        Search
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="card mt-5">
        <h4 class="card-title">List Blog</h4>
        <div class="card-body">
            <table class="table table-bordered align-middle text-center table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            Tin
                        </th>
                        @*     <th>
                        @Html.DisplayNameFor(model => model.Des)
                        </th>
                        <th>
                        @Html.DisplayNameFor(model => model.Detail)
                        </th>*@
                        <th>
                            Loại
                        </th>
                        <th>
                            Trạng Thái
                        </th>
                        <th>
                            Vị trí
                        </th>
                        <th>
                            Ngày Public
                        </th>
                        @* <th>
                        @Html.DisplayNameFor(model => model.Thumbs)
                        </th>*@

                        <th>
                            Edit
                        </th>
                        <th>
                            Delete
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td> <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                          @*  <td>
                                @Html.DisplayFor(modelItem => item.Des)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Detail)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Category)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Public)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Position)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data_pubblic)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Thumbs)
                            </td>*@
                            <td>
                                <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a>

                            </td>
                            <td>
                                @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MvcBlog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcBlog/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Test</h1>